version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: splitledger-prometheus
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: splitledger-grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

  loki:
    image: grafana/loki:latest
    container_name: splitledger-loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
